### ISSUE TITLE
Page directive fix for jsp

### ISSUE THREAD

**Issue by panthershark** [rbieber/jspcompressor#6]
JSP is getting too compressed and it needs to insure the page directive is on its own line.  Example:

<% page ...%>

&lt;div&gt;hi&lt;/div&gt;

turns would turn into this:

<% page ... %>&lt;div&gt;hi&lt;/div&gt;

This breaks when tomcat attempts to load and execute the page as the page directive must be on its own line.

**Comment by rbieber** [comment]
Never ran into this.   What version of Tomcat are you running?

**Comment by rbieber** [comment]
An update - our web app is using the latest version of tcServer (which is a latest version of Tomcat) and we are not seeing this issue.

**Comment by panthershark** [comment]
Sorry for the slow delay.  I looked at this initially and I did not see anything that would cause a failure.  One of our partners (who is supposed to be the platform expert) said that this was a page directive thing.  I submitted this ticket following that.  Turns out they were wrong and it was an issue with their code.

We can close this out.  The compressor works great.
