### ISSUE TITLE
0% compression

### ISSUE THREAD

**Issue by lakshmintenka** [rbieber/jspcompressor#9]
hi,
i have enabled debug true ,
to check whether JSP file compression happening or not.
Please find below debug line for one of the file.

[jspcompressor] Original Size: 10070, reduced to 10070 (0%)
[jspcompressor] Compressing:  $("#billingAddressphone").keypress(function(b){var a=b.keyCode||b.which;if(a===13){$("#button2").click();}});$("#addressphone").keypress(function(b){var a=b.keyCode||b.which;if(a===13){$("#button3").click();}});$(document).ready(function(){$("#button2").click(function(){var a=isFieldValueValid("billingAddressphone","N");if(a){var b=$("#myContextPath").val()+"/checkout/getAddressforPhone";$("#billingAddressphoneLabel").hide();$("#checkoutForm").attr("method","post");$("#billingAddresstownCity").attr("disabled",false);$("#checkoutForm").attr("action",b);document.getElementById("retAddrButtonCheck").value="billing";$("#checkoutForm").submit();}else{$("#billingAddressphoneLabel").show();}});});
[jspcompressor] Returning <script type="text/javascript">$("#billingAddressphone").keypress(function(c){var d=c.keyCode||c.which;if(d===13){$("#button2").click();}});$("#addressphone").keypress(function(c){var d=c.keyCode||c.which;if(d===13){$("#button3").click();}});$(document).ready(function(){$("#button2").click(function(){var d=isFieldValueValid("billingAddressphone","N");if(d){var c=$("#myContextPath").val()+"/checkout/getAddressforPhone";$("#billingAddressphoneLabel").hide();$("#checkoutForm").attr("method","post");$("#billingAddresstownCity").attr("disabled",false);$("#checkoutForm").attr("action",c);document.getElementById("retAddrButtonCheck").value="billing";$("#checkoutForm").submit();}else{$("#billingAddressphoneLabel").show();}});});</script>

Looks like compression on happening and showing 0%
My ANT task is 
<jspcompressor destdir="${compressJSP.tmp.folder}" compressjs="true" removecomments="true" removejspcomments="true" debug="true" 
            skipstrutsformcomments="true" enabled="true">
                <fileset dir="${dsgstorefront.web.webroot.folder}" includes="**/*.jsp"/>
        </jspcompressor>

**Comment by lakshmintenka** [comment]
Looks like compression not happening on NO file and showing 0%
My ANT task is 
<jspcompressor destdir="${compressJSP.tmp.folder}" compressjs="true" removecomments="true" removejspcomments="true" debug="true" skipstrutsformcomments="true" enabled="true">
                <fileset dir="${dsgstorefront.web.webroot.folder}" includes="**/*.jsp"/>
        </jspcompressor>

**Comment by rbieber** [comment]
The source is already compressed.
